//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BallisticsCalcApp.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShotInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShotInformation()
        {
            this.ShotDatas = new HashSet<ShotData>();
        }
    
        public int Id { get; set; }
        public string TargetRange { get; set; }
        public string BallisticCoefficient { get; set; }
        public string Diameter { get; set; }
        public string Velocity { get; set; }
        public string Mass { get; set; }
        public string FinalVelocity { get; set; }
        public string ImpactTime { get; set; }
        public string DensityAltidude { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShotData> ShotDatas { get; set; }
    }
}
