//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BallisticsCalcApp.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShotData
    {
        public int Id { get; set; }
        public string VelocityX { get; set; }
        public string VelocityY { get; set; }
        public string Time { get; set; }
        public string DistanceX { get; set; }
        public string DistanceY { get; set; }
    
        public virtual ShotInformation ShotInformation { get; set; }
    }
}
